field:
  x: 638
  y: 530
  size: 320
  # x_max: 958
  # y_max: 850
save_fig: true
seed: 1
solver:
  _target_: MRMP.planner3
  TIME_LIMIT: 20
  VERBOSE: 2
  epsilon: 0.3
obstacles:
agents:
  - x_init: 701
    y_init: 610
    x_goal: 701
    y_goal: 610
    rad: 18
  - x_init: 767
    y_init: 610
    x_goal: 767
    y_goal: 610
    rad: 18
  - x_init: 826
    y_init: 610
    x_goal: 826
    y_goal: 610
    rad: 18
  - x_init: 888
    y_init: 610
    x_goal: 888
    y_goal: 610
    rad: 18

  - x_init: 701
    y_init: 675
    x_goal: 701
    y_goal: 675
    rad: 18
  - x_init: 767
    y_init: 675
    x_goal: 767
    y_goal: 675
    rad: 18
  - x_init: 826
    y_init: 675
    x_goal: 826
    y_goal: 675
    rad: 18
  - x_init: 888
    y_init: 675
    x_goal: 888
    y_goal: 675
    rad: 18

  - x_init: 701
    y_init: 748
    x_goal: 701
    y_goal: 748
    rad: 18
  - x_init: 767
    y_init: 748
    x_goal: 767
    y_goal: 748
    rad: 18
  - x_init: 826
    y_init: 748
    x_goal: 826
    y_goal: 748
    rad: 18
  - x_init: 888
    y_init: 748
    x_goal: 888
    y_goal: 748
    rad: 18

  - x_init: 701
    y_init: 805
    x_goal: 701
    y_goal: 805
    rad: 18
  - x_init: 767
    y_init: 805
    x_goal: 767
    y_goal: 805
    rad: 18
  - x_init: 826
    y_init: 805
    x_goal: 826
    y_goal: 805
    rad: 18
  - x_init: 888
    y_init: 805
    x_goal: 888
    y_goal: 805
    rad: 18
